### ISSUE TITLE
New design of open wrapper

### ISSUE THREAD

**Issue by belldandyxtq** [chainer/chainerio#37]
This is a note for offline discussion:

### Summary:
A new design for open wrapper to replace the current `file_object`

### Background:
In current implementation, a decorator `open_wrapper` wraps the _original file object_ returned by open to a `fileobject`.
During the `__init__`, the `fileobject` further wraps the _original file object_ according to the underlying filesystem and the necessary to add missing functionalities to make them behave like built-in POSIX file objects.
Such `fileobject` is also a base for profiling.

### Problem:
1. Due to lack of `peek` function in `fileobject`, the pickle shows a huge performance degradation. (#36 )
2. Due to lack of `seekable` function, the nested zip container does not work (#34 )
3. Due to lack of `peek` in HDFS, the same problem in #36 would happen when using HDFS.

### Solution:
1. Add all the missing functions.
2. Stop wrapping all the file objects with `fileobject`. Instead, wrap only when it is necessary

### Decision:
We have decided on the 2nd solution.
For the 1st solution, it can be a huge work, and unnecessary for now as the profile module is not ready yet.

### Design:
Extracting the functionality of wrapping the _original file object_ from `__init__` of `fileobject`to a function, and called by the open wrapper. By doing so, we can still wrap the file object when necessary while avoid wrapping everything with `fileobject`.
This new design is supposed to fix #36 and #34.

### Todo List:

- [x]  Replace file object to a wrapper function as described in `Design`. Solves problem 1 and partially for problem 2 (except for Python <= 3.6). (#38)

- [x] Python < 3.6 seekable issue for nested zip as described in #41 . solves Problem 2 for Python <= 3.6 (#40)

- [x] `peek` for HDFS solves solves Problem 3 (#42)
