### ISSUE TITLE
Add recursive to `list`

### ISSUE THREAD

**Issue by belldandyxtq** [chainer/chainerio#46]
For containers like zip, it is a common need to list all the files, as discussed in #43. 
To support such operations in a general way, i.e. from API level, we have decided to add `recursive` flag into `list`. When set, `list` returns a generator that will walk though all the files and directories under the given path, similar to os.walk.

To-do

- [x] Add recursive to zip (#47)

- [x] Add recursive to hdfs (#49)

- [x] Add recursive to posix (#57)
